# Generated by Django 2.1.3 on 2019-09-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Указать время выполнения')),
                ('time_shift', models.PositiveIntegerField(blank=True, null=True, verbose_name='Или добавить секунды')),
                ('status', models.CharField(choices=[('0', 'Не запущено'), ('1', 'Выполняется'), ('2', 'Завершено'), ('3', 'Завершено с ошибкой')], default=('0', 'Не запущено'), max_length=12)),
                ('url', models.URLField(verbose_name='Корневая ссылка задания')),
                ('html_status', models.CharField(blank=True, max_length=4, null=True)),
                ('encoding', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('title', models.TextField(blank=True, default='', null=True)),
                ('h1', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Пользовательское задание',
                'verbose_name_plural': 'Пользовательские задания',
            },
        ),
    ]
