# Generated by Django 2.2 on 2019-08-27 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 8, 27, 19, 23, 59, 892463), verbose_name='Время создания отчета')),
                ('html_status', models.CharField(max_length=4)),
                ('encoding', models.CharField(max_length=4)),
                ('title', models.TextField()),
                ('h1', models.TextField()),
            ],
            options={
                'verbose_name': 'Отчет по заданию',
                'verbose_name_plural': 'Отчеты по заданиям',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 8, 27, 19, 23, 59, 893430), verbose_name='Время создания')),
                ('time_shift', models.DateTimeField(blank=True, verbose_name='Смещение задания по времени')),
                ('completed', models.BooleanField(verbose_name='Завершено')),
                ('status', models.CharField(choices=[('0', 'Не запущено'), ('1', 'Выполняется'), ('2', 'Завершено'), ('3', 'Завершено с ошибкой')], default='0', max_length=12)),
                ('url', models.URLField(verbose_name='Корневая ссылка задания')),
                ('report', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='h1_title_parser.ReportTask', verbose_name='Отчет по заданию')),
            ],
            options={
                'verbose_name': 'Пользовательское задание',
                'verbose_name_plural': 'Пользовательские задания',
                'ordering': ['-date'],
            },
        ),
    ]
