# Generated by Django 2.2 on 2019-08-27 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h1_title_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 27, 19, 24, 14, 778903), verbose_name='Время создания отчета'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 27, 19, 24, 14, 778903), verbose_name='Время создания'),
        ),
    ]
