# Generated by Django 2.1.3 on 2019-08-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h1_title_parser', '0003_auto_20190827_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='time_shift',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Смещение задания по времени'),
        ),
    ]
