# Generated by Django 2.1.3 on 2019-08-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h1_title_parser', '0005_auto_20190828_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertask',
            options={'verbose_name': 'Пользовательское задание', 'verbose_name_plural': 'Пользовательские задания'},
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='date',
        ),
        migrations.AlterField(
            model_name='usertask',
            name='url',
            field=models.URLField(unique=True, verbose_name='Корневая ссылка задания'),
        ),
    ]
