# Generated by Django 2.1.3 on 2019-08-28 12:34

from django.db import migrations, models
import django.utils.timezone
import h1_title_parser.validators


class Migration(migrations.Migration):

    dependencies = [
        ('h1_title_parser', '0006_auto_20190828_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, validators=[h1_title_parser.validators.only_future_time], verbose_name='Смещение задания по времени'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='time_shift',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
