# Generated by Django 2.1.3 on 2019-08-28 13:03

from django.db import migrations, models
import h1_title_parser.validators


class Migration(migrations.Migration):

    dependencies = [
        ('h1_title_parser', '0007_auto_20190828_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='completed',
        ),
        migrations.AlterField(
            model_name='reporttask',
            name='html_status',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='date',
            field=models.DateTimeField(blank=True, null=True, validators=[h1_title_parser.validators.only_future_time], verbose_name='Указать время выполнения'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='time_shift',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Или добавить секунды'),
        ),
    ]
